### ISSUE TITLE
Ошибка при проверке примера ml_example

### ISSUE THREAD

**Issue by Archij** [Wunder-Fund/wunder_challenge#3]
Добрый день! У меня всегда возникает ошибка, когда я загружаю пример ml_example. Я ложу в zip архив два файла: solution.py и ml_example.ipynb. После загрузки этого архива, идет проверка, но вконце всегда пишется "Ошибка". Второй пример simple загружается и проверяется без ошибок.

**Comment by cheremovsky** [comment]
Добрый день.
ml_example.ipynb — это Jupyter-ноутбук, в нем содержится не модель, а инструкция с кодом для того, чтобы обучить модель.
