### ISSUE TITLE
При загрузке решения из папки simple кидает ошибку

### ISSUE THREAD

**Issue by temakahap** [Wunder-Fund/wunder_challenge#4]
Не могу загрузить код из папки simple. Копирую файл (дословно), вставляю в папку, архивирую и отправляю на сабмит.

В статусе пишет, что ошибка. Вот архив, который я посылаю.
[to_score_simple.zip](https://github.com/Wunder-Fund/wunder_challenge/files/5131869/to_score_simple.zip)

**Comment by cheremovsky** [comment]
Выясняем

**Comment by cheremovsky** [comment]
Судя по всему, вы кладете в архив папку, в которой лежит submission.py
submission.py должен лежать не в папке, а в корне архива
